In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# read in the csv file as a pandas dataframe
df = pd.read_csv('bike_rentals.csv')
print(df.head())

   rental_id        date       city bike_type membership_type weather  \
0       1001  2024-01-01    Kolkata  Electric          Annual   Sunny
1       1002  2024-01-02  Bangalore    Hybrid         Monthly   Sunny
2       1003  2024-01-03    Chennai      City          Annual   Rainy
3       1004  2024-01-04    Kolkata  Mountain         Monthly   Sunny
4       1005  2024-01-05      Delhi      City          Weekly  Cloudy

  payment_method  gender  age  duration_hours  distance_km  rental_cost  \
0            UPI  Female   31             5.3         23.4       300.22
1           Card  Female   20             1.0         12.0       643.67
2            UPI    Male   41             2.4          4.4       388.47
3           Cash    Male   54             3.2         42.5       187.58
4         Wallet    Male   33             4.0         49.1       691.23

   rating  is_weekend  discount_applied
0       4        True             False
1       5       False              True
2       4        True              True
3       3       False              True
4       1       False              True

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   rental_id         500 non-null    int64
 1   date              500 non-null    str
 2   city              500 non-null    str
 3   bike_type         500 non-null    str
 4   membership_type   500 non-null    str
 5   weather           500 non-null    str
 6   payment_method    500 non-null    str
 7   gender            500 non-null    str
 8   age               500 non-null    int64
 9   duration_hours    500 non-null    float64
 10  distance_km       500 non-null    float64
 11  rental_cost       500 non-null    float64
 12  rating            500 non-null    int64
 13  is_weekend        500 non-null    bool
 14  discount_applied  500 non-null    bool
dtypes: bool(2), float64(3), int64(3), str(7)
memory usage: 51.9 KB

In [4]:
df.shape

(500, 15)

In [5]:
df

,rental_id,date,city,bike_type,membership_type,weather,payment_method,gender,age,duration_hours,distance_km,rental_cost,rating,is_weekend,discount_applied
0,1001,2024-01-01,Kolkata,Electric,Annual,Sunny,UPI,Female,31,5.3,23.4,300.22,4,True,False
1,1002,2024-01-02,Bangalore,Hybrid,Monthly,Sunny,Card,Female,20,1.0,12.0,643.67,5,False,True
2,1003,2024-01-03,Chennai,City,Annual,Rainy,UPI,Male,41,2.4,4.4,388.47,4,True,True
3,1004,2024-01-04,Kolkata,Mountain,Monthly,Sunny,Cash,Male,54,3.2,42.5,187.58,3,False,True
4,1005,2024-01-05,Delhi,City,Weekly,Cloudy,Wallet,Male,33,4.0,49.1,691.23,1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,2025-05-10,Pune,Electric,Daily,Sunny,Card,Male,51,3.9,27.7,599.75,4,True,False
496,1497,2025-05-11,Hyderabad,City,Weekly,Rainy,Card,Female,44,4.6,42.1,544.00,4,False,False
497,1498,2025-05-12,Bangalore,Hybrid,Daily,Windy,UPI,Male,58,3.7,41.4,748.67,4,False,False
498,1499,2025-05-13,Mumbai,Road,Annual,Cloudy,UPI,Female,18,0.8,42.5,665.74,4,True,True
499,1500,2025-05-14,Pune,Hybrid,Weekly,Rainy,Cash,Male,25,1.7,25.3,474.95,3,True,True

In [6]:
# count the uniques values in the weather column
df.weather.value_counts()

weather
Sunny     144
Cloudy    126
Rainy     125
Windy     105
Name: count, dtype: int64

In [7]:
df.columns

Index(['rental_id', 'date', 'city', 'bike_type', 'membership_type', 'weather',
       'payment_method', 'gender', 'age', 'duration_hours', 'distance_km',
       'rental_cost', 'rating', 'is_weekend', 'discount_applied'],
      dtype='str')

In [8]:
df.bike_type.value_counts()

bike_type
City        117
Mountain    101
Road        101
Hybrid       95
Electric     86
Name: count, dtype: int64

In [9]:
df.payment_method.value_counts()

payment_method
Wallet    132
UPI       131
Cash      121
Card      116
Name: count, dtype: int64

In [10]:
df['city'].value_counts()

city
Bangalore    82
Hyderabad    81
Pune         73
Kolkata      72
Delhi        71
Mumbai       64
Chennai      57
Name: count, dtype: int64

In [11]:
df['bike_type'].value_counts()

bike_type
City        117
Mountain    101
Road        101
Hybrid       95
Electric     86
Name: count, dtype: int64

In [12]:
# What is teh distribution of membership types ?
df['membership_type'].value_counts()

membership_type
Monthly    133
Weekly     125
Daily      124
Annual     118
Name: count, dtype: int64

In [13]:
# How many rentals occurred on weekends vs weekdays?
df['is_weekend'].value_counts()

is_weekend
True     263
False    237
Name: count, dtype: int64

In [14]:
# What percentage of rentals used each payment method?
(df['payment_method'].value_counts(normalize = True)* 100).round(2)

payment_method
Wallet    26.4
UPI       26.2
Cash      24.2
Card      23.2
Name: proportion, dtype: float64

In [15]:
# What is the gender distribution of rentels ?
df.columns
df['gender'].value_counts()

gender
Male      269
Female    202
Other      29
Name: count, dtype: int64

In [16]:
# How many rentals got each star rating?
df['rating'].value_counts().sort_index()

rating
1     26
2     54
3     96
4    195
5    129
Name: count, dtype: int64

In [17]:
# How many rentals had a discount applied vs not?
df['discount_applied'].value_counts()

discount_applied
False    349
True     151
Name: count, dtype: int64

In [18]:
# what are the  top 3 most common weather conditions during rentals?
(df['weather'].value_counts()).head(3)

weather
Sunny     144
Cloudy    126
Rainy     125
Name: count, dtype: int64

In [19]:
# What is the combined frequency of bike_type AND together?
df.groupby(['bike_type','city']).size().sort_values(ascending= False)

bike_type  city
Hybrid     Pune         22
City       Hyderabad    21
           Bangalore    21
Mountain   Bangalore    20
Road       Mumbai       20
Mountain   Hyderabad    18
Electric   Hyderabad    18
Mountain   Kolkata      18
Road       Delhi        18
           Chennai      18
City       Chennai      17
Hybrid     Kolkata      17
City       Pune         16
           Delhi        15
Mountain   Mumbai       15
Hybrid     Bangalore    15
Electric   Pune         15
           Kolkata      14
City       Mumbai       14
Road       Bangalore    14
Mountain   Delhi        13
City       Kolkata      13
Hybrid     Delhi        13
Electric   Delhi        12
           Bangalore    12
Road       Hyderabad    12
Hybrid     Hyderabad    12
Mountain   Pune         11
Road       Kolkata      10
           Pune          9
Electric   Chennai       8
Hybrid     Mumbai        8
           Chennai       8
Electric   Mumbai        7
Mountain   Chennai       6
dtype: int64

In [20]:
# What is the average rental cost per city?
df.groupby('city')['rental_cost'].mean().round(2)

city
Bangalore    472.92
Chennai      407.41
Delhi        401.28
Hyderabad    459.34
Kolkata      422.37
Mumbai       409.56
Pune         390.72
Name: rental_cost, dtype: float64

In [21]:
# What is the total distance covered per bike type?
df.columns
df.groupby('bike_type')['distance_km'].sum()

bike_type
City        3123.1
Electric    2164.6
Hybrid      2368.6
Mountain    2607.5
Road        2759.2
Name: distance_km, dtype: float64

In [22]:
# What is the average rating per membership type?
df.groupby('membership_type')['rating'].mean().round(2)

membership_type
Annual     3.73
Daily      3.58
Monthly    3.77
Weekly     3.70
Name: rating, dtype: float64

In [23]:
# How many rentals happened per weather condition?
df['weather'].value_counts()

weather
Sunny     144
Cloudy    126
Rainy     125
Windy     105
Name: count, dtype: int64

In [24]:
# What is the maximum rental duration per city?
df.groupby('city')['duration_hours'].max()

city
Bangalore    7.9
Chennai      7.9
Delhi        7.9
Hyderabad    7.9
Kolkata      7.8
Mumbai       8.0
Pune         8.0
Name: duration_hours, dtype: float64

In [25]:
# What is the min and max rental cost per bike type?
df.groupby('bike_type')['rental_cost'].agg(['max','min'])

              max    min
bike_type
City       799.17  53.99
Electric   775.82  60.79
Hybrid     799.67  50.49
Mountain   798.22  56.27
Road       797.89  64.36

In [26]:
# What is the average age of renters per gender?
df.columns
df.groupby('gender')['age'].mean()

gender
Female    40.405941
Male      41.936803
Other     37.551724
Name: age, dtype: float64

In [27]:
# what is the total revenue collected per payment method?
df.groupby('payment_method')['rental_cost'].sum()

payment_method
Card      48002.26
Cash      50590.51
UPI       57664.33
Wallet    56586.58
Name: rental_cost, dtype: float64

In [28]:
# What is the average distance per membership type?
df.groupby('membership_type')['distance_km'].mean()

membership_type
Annual     27.620339
Daily      25.170161
Monthly    24.694737
Weekly     26.866400
Name: distance_km, dtype: float64

In [29]:
# How many discounted rentals happened per city?
df[df['discount_applied']].groupby('city').size()

city
Bangalore    30
Chennai      14
Delhi        26
Hyderabad    22
Kolkata      22
Mumbai       20
Pune         17
dtype: int64

In [30]:
# What is the average rental cost per city AND bike type?
df.groupby(['city','bike_type'])['rental_cost'].mean()

city       bike_type
Bangalore  City         465.714762
           Electric     446.535833
           Hybrid       531.550667
           Mountain     457.448500
           Road         465.617857
Chennai    City         401.951765
           Electric     520.661250
           Hybrid       358.827500
           Mountain     331.590000
           Road         409.103333
Delhi      City         373.059333
           Electric     278.694167
           Hybrid       383.388462
           Mountain     465.820769
           Road         472.820000
Hyderabad  City         444.189048
           Electric     438.621111
           Hybrid       293.270000
           Mountain     542.666111
           Road         558.012500
Kolkata    City         489.449231
           Electric     445.316429
           Hybrid       430.541176
           Mountain     372.462778
           Road         378.951000
Mumbai     City         402.037857
           Electric     410.931429
           Hybrid       324.911250
           Mountain     455.431333
           Road         413.791000
Pune       City         395.579375
           Electric     445.104000
           Hybrid       367.840455
           Mountain     446.483636
           Road         279.228889
Name: rental_cost, dtype: float64

In [31]:
# Which city had the highest average rating?
df.groupby('city')['rating'].mean().sort_values(ascending = False).head(5)

city
Kolkata      3.750000
Mumbai       3.750000
Bangalore    3.719512
Pune         3.698630
Hyderabad    3.666667
Name: rating, dtype: float64

In [32]:
# What is the total revenue per city on weekends only?
df[df['is_weekend']].groupby('city')['rental_cost'].sum()

city
Bangalore    19268.17
Chennai      10394.00
Delhi        15137.79
Hyderabad    18982.37
Kolkata      16822.85
Mumbai       15829.94
Pune         17191.90
Name: rental_cost, dtype: float64

In [33]:
# get count, mean , and std of rental_cost grouped by mebership type.
df.groupby('membership_type')['rental_cost'].agg(['count','mean','std'])

                 count        mean         std
membership_type
Annual             118  416.630085  233.324487
Daily              124  410.923145  214.411034
Monthly            133  443.085414  198.749312
Weekly             125  430.372000  219.819838

In [34]:
# What is the average rental duration for each gender and weather condition?
df.groupby(['gender','weather'])['duration_hours'].mean()

gender  weather
Female  Cloudy     3.898182
        Rainy      4.196429
        Sunny      4.292000
        Windy      4.197561
Male    Cloudy     3.463077
        Rainy      4.298387
        Sunny      4.038095
        Windy      4.715517
Other   Cloudy     5.800000
        Rainy      3.285714
        Sunny      3.650000
        Windy      3.566667
Name: duration_hours, dtype: float64

In [35]:
#  How many 5-star ratings did each bike type receive?
df[df['rating']==5].groupby('bike_type').size()

bike_type
City        28
Electric    25
Hybrid      22
Mountain    26
Road        28
dtype: int64

In [36]:
#  Rank cities by total number of rentals (highest first).
df['city'].value_counts()

city
Bangalore    82
Hyderabad    81
Pune         73
Kolkata      72
Delhi        71
Mumbai       64
Chennai      57
Name: count, dtype: int64

In [37]:
# What is the percentage share of each payment method per city?
df.groupby(['city','payment_method']).size().groupby(level=0).apply(lambda x: x/x.sum()*100).round(2)

city       city       payment_method
Bangalore  Bangalore  Card              19.51
                      Cash              24.39
                      UPI               30.49
                      Wallet            25.61
Chennai    Chennai    Card              29.82
                      Cash              14.04
                      UPI               31.58
                      Wallet            24.56
Delhi      Delhi      Card              23.94
                      Cash              22.54
                      UPI               26.76
                      Wallet            26.76
Hyderabad  Hyderabad  Card              24.69
                      Cash              24.69
                      UPI               24.69
                      Wallet            25.93
Kolkata    Kolkata    Card              25.00
                      Cash              31.94
                      UPI               13.89
                      Wallet            29.17
Mumbai     Mumbai     Card              21.88
                      Cash              23.44
                      UPI               28.12
                      Wallet            26.56
Pune       Pune       Card              19.18
                      Cash              26.03
                      UPI               28.77
                      Wallet            26.03
dtype: float64

In [38]:
# Find the city-membership combination with the highest average rental cost.
avg_cost = df.groupby(['city','membership_type'])['rental_cost'].mean()
avg_cost.idxmax()

('Hyderabad', 'Weekly')